service: aws-python-rest-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  
custom:
  pythonRequirements:
    dockerizePip: non-linux
    layer:
      name: my-awesome-app-layer
      description: My awesome app layer
      compatibleRuntimes:
        - python3.8

functions:
  app:
    handler: main.handler
    events:
      - http:
          method: any
          path: /
